,cpe23Uri,titles,vulnerabilities,feedTimestamp
0,cpe:2.3:a:djangoproject:django:2.2.27:*:*:*:*:*:*:*,Django Project Django 2.2.27,[''],2022-03-20T15:31Z
1,cpe:2.3:a:djangoproject:django:3.0:*:*:*:*:*:*:*,Django Project Django 3.0,"['CVE-2019-19844', 'CVE-2020-13254', 'CVE-2020-13596', 'CVE-2020-24583', 'CVE-2020-24584', 'CVE-2020-7471', 'CVE-2020-9402', 'CVE-2021-23336', 'CVE-2021-28658', 'CVE-2021-3281', 'CVE-2021-33571']",2022-03-20T15:31Z
2,cpe:2.3:a:djangoproject:django:3.0.1:*:*:*:*:*:*:*,Django Project Django 3.0.1,"['CVE-2020-13254', 'CVE-2020-13596', 'CVE-2020-24583', 'CVE-2020-24584', 'CVE-2020-7471', 'CVE-2020-9402', 'CVE-2021-23336', 'CVE-2021-28658', 'CVE-2021-3281', 'CVE-2021-33203', 'CVE-2021-33571']",2022-03-20T15:31Z
3,cpe:2.3:a:djangoproject:django:3.0.2:*:*:*:*:*:*:*,Django Project Django 3.0.2,"['CVE-2020-13254', 'CVE-2020-13596', 'CVE-2020-24583', 'CVE-2020-24584', 'CVE-2020-7471', 'CVE-2020-9402', 'CVE-2021-23336', 'CVE-2021-28658', 'CVE-2021-3281', 'CVE-2021-33203', 'CVE-2021-33571']",2022-03-20T15:31Z
4,cpe:2.3:a:djangoproject:django:3.0.3:*:*:*:*:*:*:*,Django Project Django 3.0.3,"['CVE-2020-13254', 'CVE-2020-13596', 'CVE-2020-24583', 'CVE-2020-24584', 'CVE-2020-9402', 'CVE-2021-23336', 'CVE-2021-28658', 'CVE-2021-3281', 'CVE-2021-33203', 'CVE-2021-33571']",2022-03-20T15:31Z
5,cpe:2.3:a:djangoproject:django:3.0.4:*:*:*:*:*:*:*,Django Project Django 3.0.4,"['CVE-2020-13254', 'CVE-2020-13596', 'CVE-2020-24583', 'CVE-2020-24584', 'CVE-2021-23336', 'CVE-2021-28658', 'CVE-2021-3281', 'CVE-2021-33203', 'CVE-2021-33571']",2022-03-20T15:31Z
6,cpe:2.3:a:djangoproject:django:3.0.5:*:*:*:*:*:*:*,Django Project Django 3.0.5,"['CVE-2020-13254', 'CVE-2020-13596', 'CVE-2020-24583', 'CVE-2020-24584', 'CVE-2021-23336', 'CVE-2021-28658', 'CVE-2021-3281', 'CVE-2021-33203', 'CVE-2021-33571']",2022-03-20T15:31Z
7,cpe:2.3:a:djangoproject:django:3.0.6:*:*:*:*:*:*:*,Django Project Django 3.0.6,"['CVE-2020-13254', 'CVE-2020-13596', 'CVE-2020-24583', 'CVE-2020-24584', 'CVE-2021-23336', 'CVE-2021-28658', 'CVE-2021-3281', 'CVE-2021-33203', 'CVE-2021-33571']",2022-03-20T15:31Z
8,cpe:2.3:a:djangoproject:django:3.0.7:*:*:*:*:*:*:*,Django Project Django 3.0.7,"['CVE-2020-24583', 'CVE-2020-24584', 'CVE-2021-23336', 'CVE-2021-28658', 'CVE-2021-3281', 'CVE-2021-33203', 'CVE-2021-33571']",2022-03-20T15:31Z
9,cpe:2.3:a:djangoproject:django:3.0.8:*:*:*:*:*:*:*,Django Project Django 3.0.8,"['CVE-2020-24583', 'CVE-2020-24584', 'CVE-2021-23336', 'CVE-2021-28658', 'CVE-2021-3281', 'CVE-2021-33203', 'CVE-2021-33571']",2022-03-20T15:31Z
