,cpe23Uri,titles,vulnerabilities,feedTimestamp
0,cpe:2.3:a:django-unicorn:unicorn:0.16.1:*:*:*:*:django:*:*,Django-unicorn Unicorn 0.16.1 for Django,"['CVE-2021-42053', 'CVE-2021-42134']",2022-03-20T15:34Z
1,cpe:2.3:a:django-unicorn:unicorn:0.17.0:*:*:*:*:django:*:*,Django-unicorn Unicorn 0.17.0 for Django,"['CVE-2021-42053', 'CVE-2021-42134']",2022-03-20T15:34Z
2,cpe:2.3:a:django-unicorn:unicorn:0.17.1:*:*:*:*:django:*:*,Django-unicorn Unicorn 0.17.1 for Django,"['CVE-2021-42053', 'CVE-2021-42134']",2022-03-20T15:34Z
3,cpe:2.3:a:django-unicorn:unicorn:0.17.2:*:*:*:*:django:*:*,Django-unicorn Unicorn 0.17.2 for Django,"['CVE-2021-42053', 'CVE-2021-42134']",2022-03-20T15:34Z
4,cpe:2.3:a:django-unicorn:unicorn:0.18.0:*:*:*:*:django:*:*,Django-unicorn Unicorn 0.18.0 for Django,"['CVE-2021-42053', 'CVE-2021-42134']",2022-03-20T15:34Z
5,cpe:2.3:a:django-unicorn:unicorn:0.18.1:*:*:*:*:django:*:*,Django-unicorn Unicorn 0.18.1 for Django,"['CVE-2021-42053', 'CVE-2021-42134']",2022-03-20T15:34Z
6,cpe:2.3:a:django-unicorn:unicorn:0.19.0:*:*:*:*:django:*:*,Django-unicorn Unicorn 0.19.0 for Django,"['CVE-2021-42053', 'CVE-2021-42134']",2022-03-20T15:34Z
7,cpe:2.3:a:django-unicorn:unicorn:0.20.0:*:*:*:*:django:*:*,Django-unicorn Unicorn 0.20.0 for Django,"['CVE-2021-42053', 'CVE-2021-42134']",2022-03-20T15:34Z
8,cpe:2.3:a:django-unicorn:unicorn:0.21.0:*:*:*:*:django:*:*,Django-unicorn Unicorn 0.21.0 for Django,"['CVE-2021-42053', 'CVE-2021-42134']",2022-03-20T15:34Z
9,cpe:2.3:a:django-unicorn:unicorn:0.21.1:*:*:*:*:django:*:*,Django-unicorn Unicorn 0.21.1 for Django,"['CVE-2021-42053', 'CVE-2021-42134']",2022-03-20T15:34Z
